from checkmate import ChessBoard  # Import the ChessBoard class

# Main function to play the game.
def main():
    board = """\
........
........
..R.....
...K....
....P...
........
........
........\
"""
    chess_board = ChessBoard()  # Create a chess board instance
    chess_board.print_board()    # Display the initial board
    # Here you can implement further game logic, like moving pieces or checking for checkmate.

if __name__ == "__main__":
    main()  # Start the game.