#!/usr/bin/env python3
from checkmate import*
#Main function to play the game.
def main():
    board = """\
........
........
..R.....
...K....
....P...
........
........
........\
"""
    checkmate(board)

if __name__ == "__main__":
    main()  # Start the game.